CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Articles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" text NOT NULL,
    "Body" text NOT NULL,
    CONSTRAINT "PK_Articles" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256) NULL,
    "NormalizedName" character varying(256) NULL,
    "ConcurrencyStamp" text NULL,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetUsers" (
    "Id" text NOT NULL,
    "UserName" character varying(256) NULL,
    "NormalizedUserName" character varying(256) NULL,
    "Email" character varying(256) NULL,
    "NormalizedEmail" character varying(256) NULL,
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text NULL,
    "SecurityStamp" text NULL,
    "ConcurrencyStamp" text NULL,
    "PhoneNumber" text NULL,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone NULL,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" text NOT NULL,
    "ClaimType" text NULL,
    "ClaimValue" text NULL,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "ClaimType" text NULL,
    "ClaimValue" text NULL,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text NULL,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text NULL,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");

CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");

CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20220320161030_1_create_articles', '6.0.3');

COMMIT;

START TRANSACTION;

ALTER TABLE "AspNetUserTokens" ALTER COLUMN "Name" TYPE character varying(128);

ALTER TABLE "AspNetUserTokens" ALTER COLUMN "LoginProvider" TYPE character varying(128);

ALTER TABLE "AspNetUserLogins" ALTER COLUMN "ProviderKey" TYPE character varying(128);

ALTER TABLE "AspNetUserLogins" ALTER COLUMN "LoginProvider" TYPE character varying(128);

ALTER TABLE "Articles" ALTER COLUMN "Title" TYPE character varying(500);

ALTER TABLE "Articles" ADD "CreatedAt" timestamp with time zone NULL;

ALTER TABLE "Articles" ADD "UpdatedAt" timestamp with time zone NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20220321204144_2_create_base_entities', '6.0.3');

COMMIT;

START TRANSACTION;

CREATE TABLE "Comment" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Content" text NOT NULL,
    "Author" text NULL,
    "ArticleId" integer NULL,
    CONSTRAINT "PK_Comment" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Comment_Articles_ArticleId" FOREIGN KEY ("ArticleId") REFERENCES "Articles" ("Id")
);

CREATE TABLE "Tags" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    CONSTRAINT "PK_Tags" PRIMARY KEY ("Id")
);

CREATE TABLE "ArticleTag" (
    "ArticleId" integer NOT NULL,
    "TagId" integer NOT NULL,
    CONSTRAINT "PK_ArticleTag" PRIMARY KEY ("ArticleId", "TagId"),
    CONSTRAINT "FK_ArticleTag_Articles_TagId" FOREIGN KEY ("TagId") REFERENCES "Articles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ArticleTag_Tags_ArticleId" FOREIGN KEY ("ArticleId") REFERENCES "Tags" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_ArticleTag_TagId" ON "ArticleTag" ("TagId");

CREATE INDEX "IX_Comment_ArticleId" ON "Comment" ("ArticleId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20220321223317_3_create_comments_and_tags', '6.0.3');

COMMIT;

START TRANSACTION;

ALTER TABLE "Tags" ADD "CreatedAt" timestamp with time zone NULL;

ALTER TABLE "Tags" ADD "UpdatedAt" timestamp with time zone NULL;

ALTER TABLE "ArticleTag" ADD "CreatedAt" timestamp with time zone NULL;

ALTER TABLE "ArticleTag" ADD "UpdatedAt" timestamp with time zone NULL;

CREATE TABLE "WorkingPapers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" text NOT NULL,
    "Abstract" text NULL,
    "Link" text NOT NULL,
    "CreatedAt" timestamp with time zone NULL,
    "UpdatedAt" timestamp with time zone NULL,
    CONSTRAINT "PK_WorkingPapers" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20220322180235_4_create_working_papers', '6.0.3');

COMMIT;

START TRANSACTION;

CREATE TABLE "DataCategories" (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    CONSTRAINT "PK_DataCategories" PRIMARY KEY (id)
);

CREATE TABLE "Dataset" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Link" text NOT NULL,
    "Categoryid" integer NULL,
    CONSTRAINT "PK_Dataset" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Dataset_DataCategories_Categoryid" FOREIGN KEY ("Categoryid") REFERENCES "DataCategories" (id)
);

CREATE INDEX "IX_Dataset_Categoryid" ON "Dataset" ("Categoryid");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20220322181002_5_create_datasets_and_categories', '6.0.3');

COMMIT;

START TRANSACTION;

ALTER TABLE "Comment" DROP CONSTRAINT "FK_Comment_Articles_ArticleId";

ALTER TABLE "Comment" DROP CONSTRAINT "PK_Comment";

ALTER TABLE "Comment" RENAME TO "Comments";

ALTER INDEX "IX_Comment_ArticleId" RENAME TO "IX_Comments_ArticleId";

ALTER TABLE "Comments" ADD CONSTRAINT "PK_Comments" PRIMARY KEY ("Id");

ALTER TABLE "Comments" ADD CONSTRAINT "FK_Comments_Articles_ArticleId" FOREIGN KEY ("ArticleId") REFERENCES "Articles" ("Id");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20220430113200_CreateCommentContext', '6.0.3');

COMMIT;

START TRANSACTION;

ALTER TABLE "ArticleTag" DROP CONSTRAINT "FK_ArticleTag_Articles_TagId";

ALTER TABLE "ArticleTag" DROP CONSTRAINT "FK_ArticleTag_Tags_ArticleId";

ALTER TABLE "ArticleTag" DROP CONSTRAINT "PK_ArticleTag";

ALTER TABLE "ArticleTag" RENAME TO "ArticleTags";

ALTER INDEX "IX_ArticleTag_TagId" RENAME TO "IX_ArticleTags_TagId";

ALTER TABLE "ArticleTags" ADD CONSTRAINT "PK_ArticleTags" PRIMARY KEY ("ArticleId", "TagId");

ALTER TABLE "ArticleTags" ADD CONSTRAINT "FK_ArticleTags_Articles_TagId" FOREIGN KEY ("TagId") REFERENCES "Articles" ("Id") ON DELETE CASCADE;

ALTER TABLE "ArticleTags" ADD CONSTRAINT "FK_ArticleTags_Tags_ArticleId" FOREIGN KEY ("ArticleId") REFERENCES "Tags" ("Id") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20220501163657_CreateArticleTagsSet', '6.0.3');

COMMIT;

START TRANSACTION;

ALTER TABLE "ArticleTags" DROP CONSTRAINT "FK_ArticleTags_Articles_TagId";

ALTER TABLE "ArticleTags" DROP CONSTRAINT "FK_ArticleTags_Tags_ArticleId";

ALTER TABLE "ArticleTags" ADD CONSTRAINT "FK_ArticleTags_Articles_ArticleId" FOREIGN KEY ("ArticleId") REFERENCES "Articles" ("Id") ON DELETE CASCADE;

ALTER TABLE "ArticleTags" ADD CONSTRAINT "FK_ArticleTags_Tags_TagId" FOREIGN KEY ("TagId") REFERENCES "Tags" ("Id") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20220501201315_FixArticleTags', '6.0.3');

COMMIT;

START TRANSACTION;

ALTER TABLE "Dataset" ADD "Title" text NOT NULL DEFAULT '';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20220519191238_AddTitleToDatasets', '6.0.3');

COMMIT;

START TRANSACTION;

ALTER TABLE "Articles" ADD "Published" boolean NOT NULL DEFAULT FALSE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20220529134143_PublishedFieldArticle', '6.0.3');

COMMIT;

START TRANSACTION;

CREATE UNIQUE INDEX "IX_Tags_Name" ON "Tags" ("Name");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20220604094604_UniqueTags', '6.0.3');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20220605152238_RequiredToArticleTag', '6.0.3');

COMMIT;

START TRANSACTION;

ALTER TABLE "Dataset" DROP CONSTRAINT "FK_Dataset_DataCategories_Categoryid";

ALTER TABLE "Dataset" DROP CONSTRAINT "PK_Dataset";

ALTER TABLE "Dataset" RENAME TO "Datasets";

ALTER INDEX "IX_Dataset_Categoryid" RENAME TO "IX_Datasets_Categoryid";

ALTER TABLE "Datasets" ADD CONSTRAINT "PK_Datasets" PRIMARY KEY ("Id");

ALTER TABLE "Datasets" ADD CONSTRAINT "FK_Datasets_DataCategories_Categoryid" FOREIGN KEY ("Categoryid") REFERENCES "DataCategories" (id);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20220611152713_AddDatasets', '6.0.3');

COMMIT;

START TRANSACTION;

ALTER TABLE "Datasets" DROP CONSTRAINT "FK_Datasets_DataCategories_Categoryid";

DROP INDEX "IX_Datasets_Categoryid";

ALTER TABLE "Datasets" DROP COLUMN "Categoryid";

ALTER TABLE "DataCategories" RENAME COLUMN id TO "Id";

ALTER TABLE "Datasets" ADD "DataCategoryId" integer NOT NULL DEFAULT 0;

CREATE INDEX "IX_Datasets_DataCategoryId" ON "Datasets" ("DataCategoryId");

ALTER TABLE "Datasets" ADD CONSTRAINT "FK_Datasets_DataCategories_DataCategoryId" FOREIGN KEY ("DataCategoryId") REFERENCES "DataCategories" ("Id") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20220614180016_FixDataAndCategoriesRelation', '6.0.3');

COMMIT;

START TRANSACTION;

DROP INDEX "IX_Tags_Name";

ALTER TABLE "Datasets" ADD "CreatedAt" timestamp with time zone NULL;

ALTER TABLE "Datasets" ADD "UpdatedAt" timestamp with time zone NULL;

ALTER TABLE "DataCategories" ADD "CreatedAt" timestamp with time zone NULL;

ALTER TABLE "DataCategories" ADD "UpdatedAt" timestamp with time zone NULL;

ALTER TABLE "Comments" ADD "CreatedAt" timestamp with time zone NULL;

ALTER TABLE "Comments" ADD "UpdatedAt" timestamp with time zone NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20220621122022_InheritFromBaseEntity', '6.0.3');

COMMIT;

START TRANSACTION;

ALTER TABLE "WorkingPapers" ADD "DatasetLink" text NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20220626163627_AddDatasetLinkToWorkingPapers', '6.0.3');

COMMIT;

START TRANSACTION;

DROP TABLE "Comments";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20220811163653_RemoveComments', '6.0.3');

COMMIT;

