name: Integrate changes

on:
  pull_request:
    types: [opened]

jobs:
  integrate-changes:
    name: Integrate changes
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          token: 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

      - name: rebase feature branch onto master
        uses: cirrus-actions/rebase@1.7
        env:
          GITHUB_TOKEN: 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

      - name: setup .NET core sdk 6.0
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0

      - name: install dependencies
        run: dotnet restore

      - name: test
        run: dotnet test --no-restore --verbosity normal

      - name: merge feature branch into main
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: master
          github_token: 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
